"""add image bool to deck lists

Revision ID: 2fb3d2083c14
Revises: 9c1a732a7764
Create Date: 2021-12-24 16:23:57.934030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb3d2083c14'
down_revision = '9c1a732a7764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck_lists', sa.Column('has_image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck_lists', 'has_image')
    # ### end Alembic commands ###
