"""small changes

Revision ID: f0429ff97a89
Revises: 40a47e196af0
Create Date: 2021-12-15 14:10:20.082983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0429ff97a89'
down_revision = '40a47e196af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'emoji',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'emoji',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
