"""badges adds

Revision ID: 255bfb9e9cd0
Revises: 2fb3d2083c14
Create Date: 2021-12-27 13:43:23.680780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '255bfb9e9cd0'
down_revision = '2fb3d2083c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_badges',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('badge_id', 'user_id')
    )
    op.create_table('completed_decks',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'user_id')
    )
    op.drop_table('mastered_decks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastered_decks',
    sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], name='mastered_decks_deck_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mastered_decks_user_id_fkey'),
    sa.PrimaryKeyConstraint('deck_id', 'user_id', name='mastered_decks_pkey')
    )
    op.drop_table('completed_decks')
    op.drop_table('user_badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
