"""remove props

Revision ID: 01b0de74e473
Revises: 4ac09a1f4b67
Create Date: 2021-12-15 22:58:35.286057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01b0de74e473'
down_revision = '4ac09a1f4b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('added_decks', 'updated_on')
    op.drop_column('mastered_decks', 'updated_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mastered_decks', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('added_decks', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
